### ISSUE TITLE
iTurtleBoard  library Size 확인

### ISSUE THREAD

**Issue by rookiecj** [orocapangyo/iTurtle#9]
**결론부터 얘기하면 Atmega328P의 dynamic memory가 부족해 보인다.**

### IMAGE size feasibility
Arduino atmega 328P를 사용할 경우 IMU + ROSSerial을 포함해서 사용가능한지 image의 크기를 확인해 본다.

#### Arduino SIZE:
- storage: Maximum is 32256 bytes.
- dynamic memory:Maximum is 2048 bytes.

#### libraries
- Bolder Flight System MPU9250 by Brian Taylor
- ROSSerial Arduino Library by Michael Ferguson

#### size
- total(ram/storage):
  storage: 20428/32256 bytes (63%)
  dynamic memory: **1965/2048 bytes (95%)**
  ```
  Sketch uses 20428 bytes (63%) of program storage space. Maximum is 32256 bytes.
  Global variables use 1965 bytes (95%) of dynamic memory, leaving 83 bytes for local variables. Maximum is 2048 bytes.
  Low memory available, stability problems may occur.
  ```

- mpu
  storage: 11390/32256 bytes (35%)
  dynamic memory: 904/2048 bytes (44%)

- rosserial: ServiceServer
  storage: 10620/32256 bytes (32%)
  dynamic memory: 1245/2048 bytes (60%)

**Comment by rookiecj** [comment]
[iturtle-MPU9250.pdf](https://github.com/orocapangyo/iTurtle/files/3414834/iturtle-MPU9250.pdf)

**Comment by robertchoi** [comment]
ARDUINO LEONARDO 에서 사용하는 32 KB (ATmega32u4) of which 4 KB used by bootloader를 사용할 예정입니다.

**Comment by rookiecj** [comment]
opencr의 imu만 포팅도 진행해볼께요
